---
name: ga_s2bm_ard_3
description: Geoscience Australia Sentinel 2B MSI Analysis Ready Data Collection 3
metadata_type: eo3_sentinel_ard

license: CC-BY-4.0

metadata:
  product:
    name: ga_s2bm_ard_3
  properties:
     eo:platform: sentinel-2b
     eo:instrument: MSI
     odc:product_family: ard
     odc:producer: ga.gov.au
     dea:product_maturity: stable

measurements:
    # NBART
  - name: nbart_coastal_aerosol
    aliases:
      - nbart_band01
      - coastal_aerosol
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_blue
    aliases:
      - nbart_band02
      - blue
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_green
    aliases:
      - nbart_band03
      - green
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_red
    aliases:
      - nbart_band04
      - red
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_red_edge_1
    aliases:
      - nbart_band05
      - red_edge_1
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_red_edge_2
    aliases:
      - nbart_band06
      - red_edge_2
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_red_edge_3
    aliases:
      - nbart_band07
      - red_edge_3
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_nir_1
    aliases:
      - nbart_band08
      - nir_1
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_nir_2
    aliases:
      - nbart_band8a
      - nir_2
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_swir_2
    aliases:
      - nbart_band11
      - swir_2
      # Requested for backwards compatibility with previous collection
      - swir2
    dtype: int16
    nodata: -999
    units: '1'
  - name: nbart_swir_3
    aliases:
      - nbart_band12
      - swir_3
    dtype: int16
    nodata: -999
    units: '1'

    # Observation Attributes
  - name: oa_fmask
    aliases:
      - fmask
    dtype: uint8
    nodata: 0
    units: '1'
    flags_definition:
      fmask:
        bits: [0, 1, 2, 3, 4, 5, 6, 7]
        description: Fmask
        values:
          '0': nodata
          '1': valid
          '2': cloud
          '3': shadow
          '4': snow
          '5': water
  - name: oa_nbart_contiguity
    aliases:
      - nbart_contiguity
    dtype: uint8
    nodata: 255
    units: '1'
    flags_definition:
      contiguous:
        bits: [0]
        values:
          '1': true
          '0': false
  - name: oa_azimuthal_exiting
    aliases:
      - azimuthal_exiting
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_azimuthal_incident
    aliases:
      - azimuthal_incident
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_combined_terrain_shadow
    aliases:
      - combined_terrain_shadow
    dtype: uint8
    nodata: 255
    units: '1'
  - name: oa_exiting_angle
    aliases:
      - exiting_angle
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_incident_angle
    aliases:
      - incident_angle
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_relative_azimuth
    aliases:
      - relative_azimuth
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_relative_slope
    aliases:
      - relative_slope
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_satellite_azimuth
    aliases:
      - satellite_azimuth
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_satellite_view
    aliases:
      - satellite_view
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_solar_azimuth
    aliases:
      - solar_azimuth
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_solar_zenith
    aliases:
      - solar_zenith
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_time_delta
    aliases:
      - time_delta
    dtype: float32
    nodata: .nan
    units: '1'
  - name: oa_s2cloudless_mask
    aliases:
      - s2cloudless_mask
    dtype: uint8
    nodata: 0
    units: '1'
    flags_definition:
      s2cloudless_mask:
        bits: [0, 1, 2]
        description: s2cloudless mask
        values:
          '0': nodata
          '1': valid
          '2': cloud
  - name: oa_s2cloudless_prob
    aliases:
      - s2cloudless_prob
    dtype: float64
    nodata: .nan
    units: '1'
