---
name: esa_s2am_level1_0
description: ESA Sentinel 2A Level 0
metadata_type: eo3_sentinel

license: CC-BY-4.0

metadata:
  product:
    name: esa_s2am_level1_0
  properties:
     eo:platform: sentinel-2a
     eo:instrument: MSI
     odc:product_family: level1
     odc:producer: esa.int

measurements:
  - name: blue
    dtype: uint16
    nodata: 0
    units: '1'
  - name: coastal_aerosol
    dtype: uint16
    nodata: 0
    units: '1'
  - name: green
    dtype: uint16
    nodata: 0
    units: '1'
  - name: nir_1
    dtype: uint16
    nodata: 0
    units: '1'

  - name: nir_2
    dtype: uint16
    nodata: 0
    units: '1'

  - name: red
    dtype: uint16
    nodata: 0
    units: '1'

  - name: red_edge_1
    dtype: uint16
    nodata: 0
    units: '1'
  - name: red_edge_2
    dtype: uint16
    nodata: 0
    units: '1'
  - name: red_edge_3
    dtype: uint16
    nodata: 0
    units: '1'
  - name: swir_1_cirrus
    dtype: uint16
    nodata: 0
    units: '1'
  - name: swir_2
    dtype: uint16
    nodata: 0
    units: '1'
  - name: swir_3
    dtype: uint16
    nodata: 0
    units: '1'
  - name: water_vapour
    dtype: uint16
    nodata: 0
    units: '1'
