name: agdc
channels:
- conda-forge/label/dev
- conda-forge
- defaults
- nodefaults
dependencies:
- basemap
- bottleneck
- bqplot
- cachetools
- cartopy
- certifi
- click
- cython
- dask
- distributed
- ephem
- fiona
- flask
- folium
- future
- gdal >=1.9
- geopandas
- geopy
- glueviz
# This is only graphviz itself, not the python bindings. The latter are in the pip section.
- graphviz
- gunicorn
- h5py
- hdf5
- hypothesis
- ipdb
- ipyleaflet
- ipympl
- ipywidgets
- jplephem
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- jupyter_dashboards
- line_profiler
- luigi
- matplotlib
- memory_profiler
- mkl-service
- mock
- netcdf4
- numba
- numexpr
- numpy
- openblas
- openssl
- pandas
- pathlib
- pathlib2
- pep8
- pip
- plotly
- psutil
- psycopg2
- py6s
- pylint = 1.6.4
- pytables
- pytest
- pytest-cov
- python-dateutil
- pyyaml
- rasterio >=0.9 # required for zip reading, 0.9 gets around 1.0a ordering problems
- redis
- redis-py
- rtree
- scikit-image
- scikit-learn
- scipy
- seaborn
- shapely
- singledispatch
- spectral
- sphinx
- spyder
- sqlalchemy
- tqdm
- xarray
- pip:
  - autopep8
  - boltons
  - celery >= 4
  - ciso8601
  - compliance-checker
  - DAWG
  - graphviz
  - hdmedians
  - ipython-sql
  - modernize
  - mypy
  - opencv-python
  - perf
  - pudb
  - pydash
  - pypeg2
  - skyfield
  - structlog[dev]
  - yamllint
  - yappi
