name: agdc
dependencies:
- basemap
- bottleneck
- bqplot
- cachetools
- cartopy
- certifi
- click
- cython
- dask
- distributed
- ephem
- ffmpeg
- fiona
- flask
- folium
- future
- gdal >=1.9
- geopandas
- geopy
- glueviz
# This is only graphviz itself, not the python bindings. The latter are in the pip section.
- graphviz
- gunicorn
- h5py
- hdf5
- hypothesis
- ipdb
- ipyleaflet
- ipympl
- ipywidgets
- jplephem
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- jupyter_dashboards
- line_profiler
- luigi
- matplotlib
- memory_profiler
- mkl-service
- mock
- netcdf4
- numba
- numexpr
- numpy
- openblas
- openssl
- pandas
- pathlib
- pathlib2
- pep8
- pip
- plotly
- psutil
- psycopg2
- py6s
- pylint = 1.6.4
- pytables
- pytest
- pytest-cov
- python-dateutil
- pyyaml
- rasterio >=0.34
- redis
- redis-py
- rtree
- scikit-image
- scikit-learn
- scipy
- seaborn
- shapely
- singledispatch
- sphinx
- sqlalchemy
- tqdm
- xarray
- pip:
  - autopep8
  - boltons
  - celery >= 4
  - ciso8601
  - compliance-checker
  - DAWG
  - graphviz
  - hdmedians
  - modernize
  - pudb
  - pypeg2
  - skyfield
  - structlog[dev]
  - yappi
  - yamllint
