name: cemp_insar_alos_displacement
description: CEMP InSAR ALOS Displacement
metadata_type: eo3

metadata:
    product:
        name: cemp_insar_alos_displacement

measurements:
    - name: 'ew'
      aliases:
      - eastwest
      dtype: float32
      nodata: -9999
      units: 'mm'
    - name: 'ud'
      aliases:
      - updown
      dtype: float32
      nodata: -9999
      units: 'mm'
    - name: 'ewstd'
      aliases:
      - eastweststandarddev
      dtype: float32
      nodata: -9999
      units: 'mm'
    - name: 'upstd'
      aliases:
      - updownstandarddev
      dtype: float32
      nodata: -9999
      units: 'mm'
