name: s2_tsmask
description: |
  Time series cloud and cloud shadow detection for Sentinel-2A and Sentinel-2B surface reflectance data.

  TSmask classifies a pixel as one of the following four categories: no observation, clear, cloud, and cloud shadow.
measurements:
    - name: classification
      dtype: uint8
      flags_definition:
        classification:
            bits: [0, 1, 2, 3, 4, 5, 6, 7]
            description: TSmask classification
            values:
                '0': nodata
                '1': valid
                '2': cloud
                '3': shadow
      nodata: 0
      units: '1'
metadata:
    format:
        name: GeoTIFF
    instrument:
        name: MSI
    platform:
        code: SENTINEL_2A,SENTINEL_2B
    product_type: S2_MSI_TSmask
metadata_type: eo
