---
- hosts: all
  vars:
    remote_repo: https://github.com/GeoscienceAustralia/agdc_statistics.git
    modules_path: /g/data/v10/public/modules
    module_name: agdc-statistics
    module_version: dev
    install_root: "{{ modules_path }}/{{ module_name }}/{{ module_version }}"
    checkout_path: "{{ lookup('env', 'TMPDIR') }}/{{ module_name }}"
    python_version: "3.5"
    python_path: "{{ install_root }}/lib/python{{ python_version }}/site-packages/"
  environment:
    PYTHONPATH: "{{ python_path }}"

  tasks:

    - name: Check out Source Code to temporary path
      git:
        repo: "{{ remote_repo }}"
        dest: "{{ checkout_path }}"

    - name: Ensure destination dir exists
      file:
        path: "{{ install_root }}"
        state: directory

    - name: Install package
      shell: "python setup.py clean && python setup.py install --prefix {{ install_root }}"
      args:
        chdir: "{{ checkout_path }}"

    - name: Ensure {{modules_path}}/modulefiles/{{module_name}} exists
      file: path={{modules_path}}/modulefiles/{{module_name}} state=directory

    - name: Create modulefile
      template:
        src: module_template.j2
        dest: "{{modules_path}}/modulefiles/{{module_name}}/{{module_version}}"
        mode: 0660

